### PR TITLE
[All] Update Kubernetes dependency to v1.18.0

### PR DESCRIPTION
**Pull request by lingxiankong**
**The binaries affected**:

- [x] All
- [ ] openstack-cloud-controller-manager(OCCM)
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What this PR does / why we need it**:
Update Kubernetes dependencies to v1.18.0. Other changes in this PR:

* Remove cinder-flex-volume-driver, cinder-provisioner and manila-provisioner code from the repo.
* Fix some code to work with Kubernetes v1.18.0 modules
* Remove the job cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.15, need to add job for v1.18 instead (a follow-up action).

**Which issue this PR fixes**:
fixes #

**Special notes for reviewers**:

**Release note**:
```release-note
cinder-provisioner, manila-provisioner and cinder-flexvolume-plugin were removed from cloud-provider-openstack repository since release-1.18, use cinder-csi and manila-csi instead. Action required.
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/991)

### CODE REVIEW

**Comment by lingxiankong** [comment]
go vet (part of pull-cloud-provider-openstack-check job) is still failing:
```
$ go vet ./...
# sigs.k8s.io/sig-storage-lib-external-provisioner/v5/util
../../../pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner/v5@v5.0.0/util/util.go:106:70: not enough arguments in call to client.CoreV1().Services("k8s.io/apimachinery/pkg/apis/meta/v1".NamespaceSystem).Get
        have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
        want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
../../../pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner/v5@v5.0.0/util/util.go:109:71: not enough arguments in call to client.CoreV1().Services("k8s.io/apimachinery/pkg/apis/meta/v1".NamespaceSystem).Get
        have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
        want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
```

I've asked help in #sig-storage channel.

**Comment by ramineni** [comment]
@lingxiankong I guess we need to update release notes here , on the removal of plugins and also would be good to be marked as action required, if at all anyone uses it , will be highlighted as breaking changes of upgrade

**Comment by lingxiankong** [comment]
> @lingxiankong I guess we need to update release notes here , on the removal of plugins and also would be good to be marked as action required, if at all anyone uses it , will be highlighted as breaking changes of upgrade

You are right. PR description updated.

**Comment by ramineni** [comment]
Thanks.
/lgtm
